### ISSUE TITLE
Loading with wp_enqueue_script into WordPress

### ISSUE THREAD

**Issue by tim-rohrer** [infusion/GPS.js#10]
Hey, I was hoping to experiment with your code as part of a WordPress plugin. I'm pretty new to a lot of this, so it might be more of an issue of my not understanding what needs to happen.

Basicallly, when I try to load the `GPS.js` using `wp_enqueue_script`, Wordpress whines in the console that loading failed. Interestingly, `gps` (the handle I give it in `wp_enqueue_script()`) is shown as loaded, but `var gps = new GPS` gives and error of undefined. 

Have you used this in a plugin/php environment? Any pointers on how to wrap my head around why this doesn't load properly?

Thanks.

**Comment by infusion** [comment]
Hi Tim,

I never used the plugin in a PHP env. But as far as I understand, `wp_enqueue_script` just collects all the script files and adds them to the head or end of the body. Question is, if the JS you execute runs before the actual class is loaded. Could you add the `<script src="gps.js"></script>` tag manually to the template?

Robert

**Comment by tim-rohrer** [comment]
Initially, that didn't work either. Then I took everything out, and redid it, and I got it to work. So, I'm guessing I had something incorrect in the link.

Thanks for responding. I suspect I'll be back with a new question or two before too long :-)
