### ISSUE TITLE
Does the GPS server have to be local or can I capture the sentence from any port on the network?

### ISSUE THREAD

**Issue by tim-rohrer** [infusion/GPS.js#11]
My GPS server is integrated into my Cradlepoint router, and it is configured to provide the NMEA sentence over a particular port. I was reading through your code and examples, but I don't see a way to configure an address:port to capture the sentence. Am I missing something?

Thanks.

Tim

**Comment by infusion** [comment]
I don't know how your server sends NMEA messages. If you get the data via ajax or websockets, you can feed gps.js with the `update()` method like with the shipped examples.

**Comment by tim-rohrer** [comment]
Ok. It looks like I'll have to use another method to get, and I think I have that figured out. Then I'll use the `update()` method to parse it.

Thanks.
