### ISSUE TITLE
Error: Invalid GGA length

### ISSUE THREAD

**Issue by tim-rohrer** [infusion/GPS.js#13]
I've written a simple `node.js` server to capture the NMEA sentence transmitted from my GPS receiver. This works for a period of time, and then dies because `gps.js` throws and error of 'Invalid GGA length'. So far, I'm not seeing anything wrong with the length of the alleged offending sentence.

Here is my code:
```
const gts = new net.Server( function (socket) {
  socket.on('data', (nmea) => {
    myLatLng = nmea.toString();
    console.log(myLatLng);
      var gps = new GPS;
      gps.on('data', (parsed) => {
          console.log(parsed);
          console.log('At %s, your location was: Lat: %f, Lng: %f.', parsed.time, parsed.lat, parsed.lon);
          myLatLng = parsed;
      }); //end gps.on 
      gps.update(nmea.toString()); 
  }); // end socket.on
}); //end gts

gts.listen(PORT, function() {
  console.log('GPS Tracking Server enabled');
});
```

And here is what shows in the console (I've changed the lat/lng values for privacy, but not the checksum):

> { time: 2018-02-26T02:07:54.000Z,
>   lat: 40.00449745,
>   lon: -74.12672576666667,
>   alt: 502.6,
>   quality: 'fix',
>   satelites: 10,
>   hdop: 0.9,
>   geoidal: -20,
>   age: null,
>   stationID: null,
>   raw: '$GPGGA,020754.0,4000.269847,N,07407.603546,W,1,10,0.9,502.6,M,-20.0,M,,*6C\r\n',
>   valid: true,
>   type: 'GGA' }
> At Sun Feb 25 2018 20:07:54 GMT-0600 (CST), your location was: Lat: 40.00449745, Lng: -74.12672576666667.
> $GPGGA,020854.0,4000.269917,N,07407.603578,W,1,10,0.8,502.7,M,-20.0,M,,*6A
> 
> { time: 2018-02-26T02:08:54.000Z,
>   lat: 40.004498616666666,
>   lon: -74.1267263,
>   alt: 502.7,
>   quality: 'fix',
>   satelites: 10,
>   hdop: 0.8,
>   geoidal: -20,
>   age: null,
>   stationID: null,
>   raw: '$GPGGA,020854.0,4000.269917,N,07407.603578,W,1,10,0.8,502.7,M,-20.0,M,,*6A\r\n',
>   valid: true,
>   type: 'GGA' }
> At Sun Feb 25 2018 20:08:54 GMT-0600 (CST), your location was: Lat: 40.004498616666666, Lng: -74.1267263.
> $GPGGA,020954.0,4000.269955,N,07407.603597,W,1,10,0.8,502.9,M,-20.0,M,,*62
> $GPGGA,020955.0,4000.269955,N,07407.603597,W,1,10,0.8,502.9,M,-20.0,M,,*63
> 
> /home/tim/projects/rv-gps/node_modules/gps/gps.js:302
>         throw new Error('Invalid GGA length: ' + str);
>         ^
> 
> Error: Invalid GGA length: $GPGGA,020954.0,4000.269955,N,07407.603597,W,1,10,0.8,502.9,M,-20.0,M,,*62

I have not dug into the code nor added any error handling, but if you know of an obvious fix, please let me know.

**Comment by infusion** [comment]
Thanks for this issue! I have this harsh throwing for exactly this reason - to make people report these kind of errors and make the library more robust against a lot of different receivers. I only tested the library with a hand full of receivers.

What strange is though, when I try your stated GGA sentence, it parses correctly (except for the checksum):

```
{ time: 2018-02-26T02:09:54.000Z,
  lat: 40.00449925,
  lon: -74.12672661666667,
  alt: 502.9,
  quality: 'fix',
  satelites: 10,
  hdop: 0.8,
  geoidal: -20,
  age: null,
  stationID: null,
  raw: '$GPGGA,020954.0,4000.269955,N,07407.603597,W,1,10,0.8,502.9,M,-20.0,M,,*62',
  valid: false,
  type: 'GGA' }
```

I suppose you use the latest gps version from NPM?

BTW: You should initiate the GPS object and set the on('data') handler only once and not for every arriving packet. It does not harm, but it should save some CPU cycles for garbage collection.

**Comment by infusion** [comment]
Ahh, could you do me a favor and a `console.log(gga)` to the gps.js file, before it throws on line 302? Would be interesting, what's inside of the array at that very moment.

**Comment by tim-rohrer** [comment]
Took awhile to get it to throw: 

> [ 'GGA',
>   '152456.0',
>   '4000.270155',
>   'N',
>   '07407.603846',
>   'W',
>   '1',
>   '08',
>   '1.0',
>   '507.4',
>   'M',
>   '-20.0',
>   'M',
>   '',
>   '*60\r\n$GPGGA',
>   '152457.0',
>   '4000.270154',
>   'N',
>   '07407.603844',
>   'W',
>   '1',
>   '08',
>   '1.0',
>   '507.4',
>   'M',
>   '-20.0',
>   'M',
>   '',
>   '',
>   '62\r\n' ]
> /home/tim/projects/rv-gps/node_modules/gps/gps.js:303
>         throw new Error('Invalid GGA length: ' + str);
> 

As far as initiating the GPS object only once, thank you. I'm still learning, and had thought about that but hadn't tinkered yet. One of my knowledge gaps with `node.js` is how to pass variables.

**Comment by infusion** [comment]
hehe, I thought it is this problem. When you update your code to use `updatePartial()` instead of `update` everything should work :) Okay, here is your updated code:

```
var gps = new GPS;
gps.on('data', (parsed) => {
    console.log(parsed);
    console.log('At %s, your location was: Lat: %f, Lng: %f.', parsed.time, parsed.lat, parsed.lon);
}); //end gps.on 
const gts = new net.Server( function (socket) {
  socket.on('data', (nmea) => {
    myLatLng = nmea.toString();
      gps.updatePartial(nmea.toString()); 
  }); // end socket.on
}); //end gts

gts.listen(PORT, function() {
  console.log('GPS Tracking Server enabled');
});
```

The problem is this: Your receiver typically writes a stream of bytes. You were lucky that the receiver chunked the data most of the time correctly. `updatePartial` buffers the incoming data and as soon as a full package is available, it calls the `update`-method.

You typically don't need to use global variables. In the on(data) callback, you can use a function to work with the data. BTW: I would suggest to not use the `parsed` data directly, but use the `gps.state` object like so:

```
gps.on('data', (parsed) => {
    console.log(gps.state);
}); 
```

This has the huge advantage, that all necessary information are brought together for you to work with. So you don't have to wait for individual information of NMEA to appear. 

Robert

**Comment by tim-rohrer** [comment]
Thanks! I'm running now after changing to `updatePartial`, and will let you know if there are more issues with it.

BTW, what was your clue? Is it because elements of GGA were out of order?

**Comment by infusion** [comment]
The clue was that the first message was parsed correctly, but the next message was already part of the current data. You can see that, that somewhere in the middle the two messages are separated with \r\n. `updatePartial` splits the messages at \r\n, which `update` does not. `update` expects a valid message from $ ... *00 where 00 is the checksum of the message.

**Comment by tim-rohrer** [comment]
Perfect. I thought that was the case.
