### ISSUE TITLE
GST not yet supported in current release

### ISSUE THREAD

**Issue by connyhald** [infusion/GPS.js#14]
The README states that GST messages are supported. However that GST parsing code is only in master and not yet part of any release.

I know this is motly a Github issue as it shows the README file from master. Still maybe this ticket could stay here for others until the code has been released - would have saved me some debugging :)

Latest release 0.4.0 - Aug 1,  2017
Support for GST added - Oct 6, 2017

**Comment by infusion** [comment]
Hi Cornelius,
thanks for opening the issue.  I have some things on my list before I wanted to publish the next release. But this shouldn't be a shop stopper for you, I'll make a minor release now.
Robert

**Comment by infusion** [comment]
Done :) Have fun with gps.js

**Comment by connyhald** [comment]
Thanks a lot - that's really nice of you! And yes, I'm having fun, it's a great library :)
