### ISSUE TITLE
"Satelites" should be spelled "satellites" 

### ISSUE THREAD

**Issue by tim-rohrer** [infusion/GPS.js#15]
Just noticed tonight that the parser misspells the word, and it should have to of the letter 'l'.

Although minor, it could cause confusion if someone were trying to reference the field.

Thanks.

**Comment by infusion** [comment]
Okay, fixed it :) Sorry for that typo.

**Comment by tim-rohrer** [comment]
Boom! And it is already available through the npm packages. All I had to do was go sleep for a bit.

Thanks!
