### ISSUE TITLE
Serial port closes after some time and gps.js randomly throws errors

### ISSUE THREAD

**Issue by all2pie** [infusion/GPS.js#17]
I am using neo 6m gps module with raspberry pi 3 , i have attached it on serial port ttyAMA0 , but it reads data for only small time and then port closes automatically , and sometime gps.js module to throw an error.
Here is my edited version of maps example : 
``` node

var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);


var file = '/dev/ttyAMA0';

const SerialPort = require('serialport');
const parsers = SerialPort.parsers;

const parser = new parsers.Readline({
  delimiter: '\r\n'
});

const port = new SerialPort(file, {
  baudRate: 9600
});

port.pipe(parser);


var GPS = require('../../gps.js');
var gps = new GPS;

gps.on('GGA', function(data) {
  io.emit('position', data);
  console.log("Latitiude :", data.lat);
  console.log("Longitude :", data.lon);
});

app.get('/', function(req, res) {
  res.sendFile(__dirname + '/maps.html');
});

http.listen(3000, function() {

  console.log('listening on *:3000');
});

port.on('data', function(data) {	
  gps.updatePartial(data);
});

process.on('unhandledRejection', function (reason, p) {
  //I just caught an unhandled promise rejection, since we already have fallback handler for unhandled errors (see below), let throw and let him handle that
  console.log("=============");
  console.log(reason);
  console.log("=============");
  return;
});

process.on('rejectionHandled', () => {});

process.on('uncaughtException', function (error) {
	console.log(error);
});

port.on('close', function(data) {
	
  console.log("Port closed");
  console.log(port.binding);
	
	});

```
![Output](https://user-images.githubusercontent.com/34629684/46064911-237f6800-c18a-11e8-9d95-2ce5c05008ae.png)

Please help me with the issue i will be very grateful.

**Comment by infusion** [comment]
Sorry, I missed the email notify for this issue. I will look into it.

**Comment by infusion** [comment]
Okay, I tested your message `$GPVTG,,,,,,,,,MZDA,073524.491,26,09,2018,00,00*5B` and it appears that the message is invalid. At the end you have a checksum and this checksum does not match, so the library works correctly. I think the problem you have is either a lose solder joint or a broken GPS receiver. Double check your wiring and if this does not work, try another receiver.

**Comment by all2pie** [comment]
Thanks, it was some kernal or some software issues, i reinstalled raspbian
and it worked just fine 🙂

**Comment by infusion** [comment]
Nice to hear that and sorry for my late response.

**Comment by all2pie** [comment]
No problem 🙂
