### ISSUE TITLE
Invalid GLL length

### ISSUE THREAD

**Issue by alban-ameti** [infusion/GPS.js#23]
Hi,

I get the following error:
Invalid GLL length: $GPGLL,5000.05254,N,04500.02356,E,090037.059,A*35
when using a GPS simulator https://gpsgate.com/support/gps_simulator

I don't know enough about the message standard to know if this is the simulators fault and its not generating the data in the correct format...

This is my code:

const path = 'COM2'
const SerialPort = require('serialport')
const parsers = SerialPort.parsers
const parser = new parsers.Readline({
  delimiter: '\r\n'
})
const port = new SerialPort(path, {
  baudRate: 4800
})

port.pipe(parser)

let GPS = require('gps')
let gps = new GPS

gps.on('data', function(data) {
  console.log(data)
})

parser.on('data', function(data) {
  gps.update(data)
})

**Comment by infusion** [comment]
Thanks for reporting this issue. The generator seems to produce NMEA sentences prior to version 2.3, so now FAA field is supported. It is fixed and published. 
Sorry for the harsh policy of throwing errors as soon as something goes wrong, but I want to get these issues reported to make the library much more robust for a variety of devices.

**Comment by alban-ameti** [comment]
All good thanks for the support! :) I am gonna do some more testing with this and let you know if I find more issues.
