### ISSUE TITLE
solution for make the weft more reliable ?

### ISSUE THREAD

**Issue by TIB28** [infusion/GPS.js#24]
Hi, tx for ur job i am using your module for my gps iot project but i didn't find any data to be sure of my lat/lon , no TTFF or other information about the fix , do u have a solution for good and reliable tracking lat/lon

**Comment by infusion** [comment]
I think it depends on your receiver. My receiver sets DOP values to 99.9 until a fix is established. Furthermore, you could use the GGA quality measure to know if you got a fix.

**Comment by TIB28** [comment]
ok thanks u , i need to familliar with DOP information  of GGA weft it's possible to include some "RMC" information  with GGA weft in same data statement ?

**Comment by TIB28** [comment]
because i need speed in km/h if i not use RMC weft i necessary calculate the speed with the dist/sec =//

**Comment by infusion** [comment]
How do you think of that information in detail? The messages GGA and RMC are passed as is. I don't understand your last post. Every speed measure is given as km/h. To calculate the speed yourself, you can use the `GPS.Distance` function between the current and the previous location, divided by the time difference. If this information is too noisy, you can filter the data to get a clean and stable signal.

**Comment by TIB28** [comment]
![Sans titre2](https://user-images.githubusercontent.com/47740872/57620180-4aa77000-7588-11e9-9de2-8a648e767a82.png)

it's an screenshot of my front and tty of raspberry where the receiver is connected, i'm in building and i dont move but my app see many movement , and i give u a part of my app.js :

https://paste.ofcode.org/37mgz6DhqJyi3gXP9z3SJig

i want to collect data of one RPI in a car with CAN and GPS Data to my backend "KUZZLE" and display the data to my front in vuejs all is good exept the location when we are in the building but outside no pb it's realy  strange because it's a good receiver "garmin gp18x PC".

**Comment by infusion** [comment]
Okay, two things:
First, GPS works with satellites that need to be visible. Mountains or buildings are a big problem outside and can result in big imprecision. Location indoor is even harder and hot topic in the academic community.
Second, satellites move with several thousand km/h around the globe and new satellites enter the network all the time. These satellites bring in new information or lose information and thus result in jumps on the map. This also happens with a solid fix. GPS does not have cm precision, but can jump within 1-100m, depending on your receiver and conditions.

Okay, but how can you avoid these problems? It depends on your use-case. Either you bring in more information (wifi location, odometry, pedometry, IMU data and so on), which is called sensor fusion and a very hot research area (topic of my thesis back than). Or, alternatively, you bring in a filter to "average" the signal in a clever way. The easiest is a low-pass filter/complementary filter (which was implemented in the examples before) or a Kalman Filter (now implemented in the examples and is a "learning" low-pass filter based on the variance). I would go with a low-pass if you are new to the topic, which does not have perfect results but Kalman filters (plus maybe sensor fusion) may stop your development for quite some time. To get you a start, here is a very simple low-pass implementation:

```
let lat = 0;
let lon = 0;
function update(data) {
   const alpha = 0.2;
   lat = alpha * lat + (1 - alpha) * data.lat;
   lon = alpha * lon + (1 - alpha) * data.lon;

  // now use lat and lon for your position
}
```

You have to adjust the alpha value by hand. 0.2 means 20% of the old value is used, and 80% of the new value. This "averages" in a way and the bigger alpha gets, the more stable your value becomes - with the cost that movement is not detected right away.

**Comment by TIB28** [comment]
Ok, 
thank you very much for all this information ,it's all that I miss the way to implement the dataLAT/LON with an hysteresis or delta ur short code is "THE GRAIL" =D

**Comment by infusion** [comment]
As I said, it's only the beginning of a way of getting a more accurate estimate of the true location, but it helps reducing the noise in the first place, which should be okay for a hobby project.

**Comment by TIB28** [comment]
thanks u infusion it work perfectly =),  have a nice day and good continuation to u.
