### ISSUE TITLE
Invalid GGA length

### ISSUE THREAD

**Issue by alban-ameti** [infusion/GPS.js#25]
Hi There,

I noticed some more errors trying to process the following GGA data:

$GPGGA,033016,1227.2470,S,13050.8514,E,2,6,0.9,11.8,M,,M*4A
$GPGGA,033631,1227.2473,S,13050.8504,E,2,6,0.9,7.4,M,,M*70
$GPGGA,034030,1227.2475,S,13050.8528,E,2,6,0.9,8.1,M,,M*72

**Comment by infusion** [comment]
Thanks, seems your receiver is leaving out the last two fields for DGPS information. I made them optional for your format.
