### ISSUE TITLE
GPS.DISTANCE returns distance in km rather than meters as specified in the function protoype.

### ISSUE THREAD

**Issue by srich36** [infusion/GPS.js#27]
Relevant files:
1. `gps.js`
2. `gps.d.ts` (for documentation)

The static method GPS.HEADING returns the distance between two lat/long pairs in km rather than meters as specified above the function definition. This is not a big issue as it is just a documentation fix; I just thought it would be helpful since hovering over the function in text editors/IDE's often display the function documentation which specifies the return value will be in meters. In the future this may save some people time (albeit not much) by not requiring them to verify from the source.

**Comment by infusion** [comment]
Good finding, thanks! I changed it :)

**Comment by jrcichra** [comment]
I don't believe this is fixed in 0.5.3 on npm. I'm still seeing the documentation issue in late Nov 2019:

![image](https://user-images.githubusercontent.com/1342149/69513283-4d125b80-0f15-11ea-8d8b-4036cdf71a86.png)
I was presently surprised that the number I received was off by a factor of 1000!
