### ISSUE TITLE
can you add altitude to kalman filter?

### ISSUE THREAD

**Issue by vinnitu** [infusion/GPS.js#28]
Hello!

I have rocket model with gps and use your module with kalman filter but it does not use altitude\height. Can you add altitude to filter too?

Thanks

**Comment by infusion** [comment]
Hmm, yes that would be no problem to add, but I wonder what the practical benefit is. The altitude of GPS is by nature very inaccurate and would need to be fused with an external sensor, like an air-pressure sensor (BMP180 or the like), especially for a model rocket, where the altitude is crucial. So I think deriving the KF for your special use case would be of more value. If you need help with the math, I can help on that.
