### ISSUE TITLE
Error: Invalid RMC length

### ISSUE THREAD

**Issue by antonysimstonlivera** [infusion/GPS.js#30]
Hello!
Using VDB-800SG (ublox 6 with G-sensor) for fetching nmea.
But, getting Invalid RMC length error randomnly while parsing it with gps.js. 

Error: Invalid RMC length: $GNRMC,132452.00,A,4109.76817,N,00838.23846,W,0.120,,170320,,,A*$GNVTG,,T,,M,0.120,N,0.222,K,A*3C

Code which is being used: 
   .......

    gps.on('data', function(parsed) {
        console.log('Lat: %f, Lng: %f.', gps.state.lat, gps.state.lon);
    });

    gpsPort.on('data', function(nmea) {                
        try {
            gps.updatePartial(nmea);
        } catch (error) {
            console.log('ERROR IN UPDATE PARTIAL:::'); 
        }
    });

Please help. 
Thanks.

**Comment by infusion** [comment]
Hi,

this message looks corrupted. For the RMC packet, the checksum after * is missing (maybe also the `\r\n` is missing) and then the VTG message starts right within the first message.

Does this happen occasionally or is this the first message you get?

**Comment by antonysimstonlivera** [comment]
Hi!
It happens randomnly. 
Another 'raw' which does not throw error: 
$GNRMC,203214.00,A,4109.77261,N,00838.23718,W,0.077,,170320,,,A*78

Had parser with new line character too:
```
let gpsPort = new SerialPort('/dev/ttyACM0', { 
    baudRate: 9600, 
    parser: new SerialPort.parsers.Readline('\r\n')
});
```
Thanks.

**Comment by infusion** [comment]
Why should it throw an error? I don't see a mistake here

**Comment by theprojectsomething** [comment]
I'm getting this same random error, also on a ublox.

Same issue - RMC line is sometimes missing the checksum and getting concatenated with the following VTG line. Doesn't seem to be much difference between the data being sent (see below).

Could you consider using `$GP` to delineate messages rather than just newlines?

Alternatively, following an error, would it be feasible to remove the invalid chunk from the partial so as to allow the state to be recoverable? Currently the partial retains the invalid chunk, causing all subsequent (valid) chunks to similarly fail to parse.

Valid update:
```
$GPRMC,060912.00,A,1234.5678,S,1234.5678,E,0.300,,281120,,,A*6F
$GPVTG,,T,,M,0.300,N,0.556,K,A*26
$GPGGA,060912.00,1234.5678,S,1234.5678,E,1,07,1.10,25.1,M,59.1,M,,*74
$GPGSA,A,3,10,15,18,26,20,29,23,,,,,,2.34,1.10,2.07*02
$GPGSV,3,1,12,05,09,143,,10,25,321,28,12,20,019,18,13,14,104,*7C
$GPGSV,3,2,12,15,37,075,16,18,42,216,26,20,59,301,23,23,57,315,19*71
$GPGSV,3,3,12,25,51,348,09,26,20,229,23,29,56,146,21,31,04,283,20*74
$GPGLL,1234.5678,S,1234.5678,E,060912.00,A,A*7D
```

Immediately followed by an invalid update:
```
$GPRMC,060913.00,A,1234.5678,S,1234.5678,E,0.346,,281120,,,A*$GPVTG,,T,,M,0.346,N,0.641,K,A*21
$GPGGA,060913.00,1234.5678,S,1234.5678,E,1,07,1.10,24.9,M,59.1,M,,*74
$GPGSA,A,3,10,15,18,26,20,29,23,,,,,,2.34,1.10,2.07*02
$GPGSV,3,1,12,05,09,143,,10,25,321,28,12,20,019,18,13,14,104,*7C
$GPGSV,3,2,12,15,37,075,15,18,42,216,25,20,59,301,22,23,57,315,20*7A
$GPGSV,3,3,12,25,51,348,08,26,20,229,24,29,56,146,22,31,04,283,20*71
$GPGLL,1234.5678,S,1234.5678,E,060913.00,A,A*74
```

All subsequent valid updates fail to parse.

**Comment by infusion** [comment]
@theprojectsomething Does your PR fix this behavior already?

**Comment by theprojectsomething** [comment]
@infusion apologies the PR came after the fact, it addresses the error state. Figured that, given the checksum wouldn't be available, you could safely discard the message and leave it at that.
