### ISSUE TITLE
regarding previous Issue on kalman filter

### ISSUE THREAD

**Issue by pedefe** [infusion/GPS.js#36]
Hi,
The previous "issue" write about "add altitude to Kalman filter".
Does the module already "adjust" lat & lon with Kalman filter ?
I try with a small GPS device (HiLetgo GY-NEO6MV2 NEO-6M GPS Flight Controller Module 3V-5V with Ceramic Antenna for Arduino EEPROM APM 2.5, https://www.amazon.fr/gp/product/B07B4658XJ/ref=ppx_yo_dt_b_asin_title_o06_s00), but the position is not stable and move when vehicle is stopped ? May be  a problem of quality of my device ? or an interpolation in your code ?
Best regards.

**Comment by infusion** [comment]
First no, gps.js does not serve a Kalman Filter. It is only shipped in the examples folder, since the KF setup would need so many config parameters/matrices that people can write the KF directly on their own (using Kalman.js for example)

So the code is not interpolating anything. The unstable altitude is due to the precision of your GY-NEO6MV2, which is known to have about 10m fluctuations in all 3 dimensions.

I would suggest to use a pressure sensor like the BME280 or similar to get an altitude measure in the cm range.

**Comment by pedefe** [comment]
Thank you very much.
Is there a medium-cost GPS device, interfaced with USB/TTL (under 50€), working with raspberry, which has a correct precision ?
Best regards.

**Comment by infusion** [comment]
For the price GY-NEO6MV2 is quite okay. You have to know its limits, like big jumps on satellite change and GPS-only satellites (no GLONASS or Galileo). Filtering can help a lot here, but I would a) add a low cost BME280 for altitude and b) If you use a Kalman Filter, model your physical application as the foundation to make the system much more robust (requires a fairly deep amount of understanding of KF).

It might exhaust your budget, but if you need cm precision, take a look at u-blox F9 series, I really would love to get my hands on one of those as well.

**Comment by pedefe** [comment]
Hello,
If you switch to u-blox, you change for a professional provider ( I met them on a trade show in Paris). In my job, I use UNEX PCB-201 for C-ITS/V2X solution, (with UNEX VTX 201 for ITS-G5 communication), and performance are not the same. 
I will search something between two extremes...
Best regards.

**Comment by infusion** [comment]
Hi,

cool field you're working in! The problem with GPS is, it highly depends on your use-case. When you are on a flat terrain with no trees and houses, it's much easier to get a 3D fix and thus also a better altitude accuracy. You could have a look at Sparkfuns GPS-15712 (2m accuracy) or if you can afford a little more, have a look at Piksi ( https://www.swiftnav.com/piksi-multi ) or Ardusimple.

Robert
