### ISSUE TITLE
Issue parsing BDGSV

### ISSUE THREAD

**Issue by Pupix** [infusion/GPS.js#38]
Hello,

Sometimes the raw data coming from BeiDou satellites has an extra `0,` between the satellite data and the checksum. This causes the module to throw when checking the GSV array length.
https://github.com/infusion/GPS.js/blob/2f6eff60a0e70dbdb5d59cc0d860940a4cb64fe5/gps.js#L497

Here's some raw data examples:

```
$GLGSV,3,1,09,78,33,298,28,88,12,160,20,87,38,120,24,67,28,232,32,1*7B
$GLGSV,3,2,09,68,34,293,25,86,28,040,,77,59,023,,76,21,075,,1*7B
$GLGSV,3,3,09,69,08,338,,1*4E
$GPGSV,4,1,13,02,10,135,20,10,03,278,21,12,63,277,27,13,06,161,22,1*6A
$GPGSV,4,2,13,15,22,187,29,17,14,039,16,19,34,050,19,24,83,081,28,1*63
$GPGSV,4,3,13,25,26,260,28,06,15,091,,23,,,,32,13,319,,1*5F
$GPGSV,4,4,13,49,,,34,1*6C
// Breaks from here on out
$BDGSV,4,1,16,01,,,37,02,,,38,03,,,39,05,,,37,0,4*6A
$BDGSV,4,2,16,06,,,32,07,,,36,08,,,32,09,,,30,0,4*6B
$BDGSV,4,3,16,10,,,35,11,,,37,13,04,092,31,15,,,32,0,4*55
$BDGSV,4,4,16,16,,,34,17,,,33,19,,,32,20,,,34,0,4*61
```

For now I monkey patched the GSV parser removing the length check and haven't noticed any problems.

I am wondering if this is a common issue with that kind of satellites and should skip their data or it can be solved at a library level.

Cheers,

**Comment by infusion** [comment]
Strange package, I googled around for other BD GSV data sets and yours is quite unique. Even the Beidou documentation does not contain another field. But thanks a lot for reporting this issue and making GPS.js better!

Robert
