### ISSUE TITLE
GDOP and Hv

### ISSUE THREAD

**Issue by smolleyes** [infusion/GPS.js#39]
hi!

wish you re right since you helped me on my F9P problems :)

one of the company i work with ask me the GDOP and Hv values ???

is it possible to add it to the lib ? (can t find informations on this "Hv" thought)...

thanks !

**Comment by infusion** [comment]
I think it depends on what you or your employer is trying to achieve. The definition of GDOP according to [1] is

<img width="567" alt="image" src="https://user-images.githubusercontent.com/197742/205159763-272f329d-2588-406a-97de-a2b034fa6a9c.png">

From that follows that you could calculate the GDOP based on the PDOP or HDOP and VDOP as well as TDOP if you have it. However, I don't know a receiver that gives you that information. Which brings me back to the question: What are you trying to achive?

[1] Kalman Filtering Theory and Practice with MATLAB by Mohinder S. Grewal, Angus P. Andrews

**Comment by infusion** [comment]
Maybe this paper is of help to achieve your goal https://stc.fs.cvut.cz/history/2011/sbornik/papers/pdf/1100016-1.pdf

**Comment by smolleyes** [comment]
hi!

thanks for your help, too much maths in the pdf for me :)

i think i ll find something for the GDOP but can t find any information on this "Hv"

to understand, after each end of construction (we are an asbestos diagnostic company, we do coring in road asphalt to find the asbestos), so we need very precise gps reports.., my client ask me to send the report and an extra CSV with this data :

X/Y/Z positions (ok) | total satellites in use when photo was taken | Hv | PDOP < 2 | GDOP < 2 | HDOP < 2 ....

actually i have it all but the Hv and GDOP, i found a solution to store some infos in the exif of my photos, result :
User Comment                    : {"satellites":9,"PDOP":1,"HDOP":0.7,"VDOP":0.7}

thanks !

**Comment by smolleyes** [comment]
lolllll, just asked to OPENAI ... (we re fucked)

reply:

my question -> comment calculer le GDOP d'un relevé GPS, affiche la forumule et un exemple:

reply:

Le GDOP (Global Dilution Of Precision) est un indicateur qui mesure la qualité d'un relevé GPS. Plus le GDOP est faible, plus la précision du relevé est élevée.

La formule pour calculer le GDOP est :

GDOP = sqrt(PDOP^2 + HDOP^2 + VDOP^2)

où PDOP est la Dilution Of Precision Planimétrique, HDOP est la Dilution Of Precision Horizontale et VDOP est la Dilution Of Precision Verticale.

Par exemple, si le PDOP est 1.5, le HDOP est 2.0 et le VDOP est 3.0, alors :

GDOP = sqrt(1.5^2 + 2.0^2 + 3.0^2)
= sqrt(2.25 + 4.0 + 9.0)
= sqrt(15.25)
= 3.9

**Comment by smolleyes** [comment]
same for HV... (that s crazy) reply:

La formule pour calculer le Hv (hauteur verticale) d'un relevé GPS est la suivante : 

Hv = Hp - Hg

Où : 
Hp = hauteur du point
Hg = hauteur du géoïde

Exemple en Javascript : 

let Hp = 100;
let Hg = 50;
let Hv = Hp - Hg;
console.log(Hv); // Affiche 50

**Comment by smolleyes** [comment]
so... problem fixed for the GPOD ...

in exif i have my value now...:

 {"satellites":3,"PDOP":1.3,"HDOP":1,"VDOP":0.8,"GDOP":1.824828759089466}

**Comment by infusion** [comment]
According to the equations I posted your calculation is wrong. GDOP can therefore be calculated with

GDOP = sqrt(PDOP^2 + TDOP^2)

or

GDPÜ = sqrt(HDOP^2 + VDOP^2 + TDOP^2)

as I already said.  Maybe it can be defined like that but what you calculate I don't know.

**Comment by smolleyes** [comment]
hi

finally client was unable to explain why they need those values... i sticked to V/P/HDOP  only and that s fine :) 

thanks !
