### ISSUE TITLE
No latitude longitude found in dashboard example

### ISSUE THREAD

**Issue by kaushik-hemant** [infusion/GPS.js#4]
Hi 

Currently i attached a gps receiver with linux server but it doesnt shows the gps data
![image](https://cloud.githubusercontent.com/assets/15911296/21260520/544e04b0-c3ac-11e6-88cd-db21f8fd9d88.png)

**Comment by infusion** [comment]
It actually gets data, but it doesn't have a fix. It's either a https://en.wikipedia.org/wiki/Time_to_first_fix issue, which means u just have to wait more time or you have a really poor signal. Seeing only 6 satellites could also be this. Having a strong GPS signal indoors, is quite unusual.
