### ISSUE TITLE
Adding state['heading'] for $GPHDT

### ISSUE THREAD

**Issue by aerodyz** [infusion/GPS.js#41]
Hello,

Is it possible for you to adding the heading state when we update the GPS with a "$GPHDT" ?

We just need to add the following code at L.27 in gps.js :

`if (data['type'] === 'HDT') {
      state['heading'] = data['heading'];
      state['trueNorth'] = data['trueNorth'];
 }`

Thanks a lot !

Alex.

**Comment by infusion** [comment]
Nice addition, I added it! Thanks!
