### ISSUE TITLE
Example issue

### ISSUE THREAD

**Issue by Craytor** [infusion/GPS.js#5]
Hello!

I'm trying to run the example dashboard script but I keep getting the following error, any suggestions?

```
Tylers-iMac:dashboard tyleryouschak$ node server.js 
/Users/tyleryouschak/Desktop/GPS.js/examples/dashboard/server.js:14
  parser: SerialPort.parsers.readline('\r\n')
                             ^

TypeError: SerialPort.parsers.readline is not a function
    at Object.<anonymous> (/Users/tyleryouschak/Desktop/GPS.js/examples/dashboard/server.js:14:30)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

There looks to be an issue with the readline parser not being available, but I'm not familar with the SerialPort library.

**Comment by infusion** [comment]
Hmm, I should version-pin serialport. Seems you need to update it.

**Comment by Craytor** [comment]
I've done some investigating and I found that locking serial port to 4.0.7 works great. They must have changed some things in 5.0.0.

```"serialport": "^4.0.7",```

Also, I'm wanting to use your GPS.js library in an Electron app - do you expect that this should work?

**Comment by infusion** [comment]
Oh, you're right. I'll check out what's new. Thanks!

It should work with electron without any problems. Only thing you need to do is set up the callbacks.

**Comment by Craytor** [comment]
Okay awesome. Will let you know how it works or if I run into any issues. I will close this issue for now.

**Comment by infusion** [comment]
Ahh, they changed the parsers to be stream transforms now.

**Comment by infusion** [comment]
Give me 10min, I'll update the examples to make them work with serialport v5

**Comment by Craytor** [comment]
Okay, thats fine! Thanks for looking into it also!

I'm about to step out of the office for a few hours, but will be back later.

**Comment by infusion** [comment]
Okay, done :)
