### ISSUE TITLE
GPS Port Check

### ISSUE THREAD

**Issue by Craytor** [infusion/GPS.js#6]
Is it possible to add a layer / functionality to check to see if a selected port is a gps? If it isn't then throw an error and stop the gps and serialport instance?

Just a thought and suggestion!

**Comment by infusion** [comment]
I think you can do this already by simply open a port and exit if the gps parser isn't able to parse something. It's more an examples addition than a feature of the library itself.

**Comment by infusion** [comment]
What I mean by that is simply try to `GPS.Parse(data)` and if the return value is `false` you know it's not a valid nmea sentence.
