### ISSUE TITLE
Dashboard Examples Issue

### ISSUE THREAD

**Issue by ilyhel** [infusion/GPS.js#7]
Hello , I run the dashboard Examples on windows 10 pc but i get this issue :  
 listening on *:3000
(node:16360) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Opening /dev/ttyS1: Unknown error code 3.

I can acces to the dashboard from my phone on this adress "http://192.168.8.103" but i get all values empty :( .

**Comment by infusion** [comment]
When you `tail -f /dev/ttyS1` you can see the data stream?

**Comment by ilyhel** [comment]
Thank you for your  response but wich device ?  because my requirement is to get phone location when i browse to "http://192.168.8.103:3000" from mobile.

**Comment by infusion** [comment]
The device `/dev/ttyS1`, where your GPS receiver is connected to. This package is not about getting user media data, like location of your smartphone but parsing raw gps information and get the information out of it.

**Comment by ilyhel** [comment]
Ok thanks a lot  but i guess i can parse data from my smartphone using gps.js ?

**Comment by infusion** [comment]
yes, but your smartphone does not provide gps raw information but gives you limited information to latitude and longitude without the need to parse it

**Comment by ilyhel** [comment]
Thank you for your response :)
